// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGymAURdEGIBm2OLFJ8DLJRhSX0q-0n1Q',
    appId: '1:53076913016:web:5530f9b8bd1f2f8364f68d',
    messagingSenderId: '53076913016',
    projectId: 'cartwala-202c2',
    authDomain: 'cartwala-202c2.firebaseapp.com',
    storageBucket: 'cartwala-202c2.firebasestorage.app',
    measurementId: 'G-H8KD7WNZTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQ9GLJ3KSKkGHRp4_i8WNOtV4yFTgl58',
    appId: '1:53076913016:android:977c9754c254395b64f68d',
    messagingSenderId: '53076913016',
    projectId: 'cartwala-202c2',
    storageBucket: 'cartwala-202c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Y_aypxGlqEjcZSf9YQMZ6rIu3PORcYU',
    appId: '1:53076913016:ios:425260f91ce4859a64f68d',
    messagingSenderId: '53076913016',
    projectId: 'cartwala-202c2',
    storageBucket: 'cartwala-202c2.firebasestorage.app',
    iosBundleId: 'com.example.cartwala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Y_aypxGlqEjcZSf9YQMZ6rIu3PORcYU',
    appId: '1:53076913016:ios:425260f91ce4859a64f68d',
    messagingSenderId: '53076913016',
    projectId: 'cartwala-202c2',
    storageBucket: 'cartwala-202c2.firebasestorage.app',
    iosBundleId: 'com.example.cartwala',
  );
}
